from django.db import models
from django.contrib.auth.models import AbstractUser

# 1. User Table
class User(AbstractUser):
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.username})"

# 2. User_Profile Table (UPGRADED)
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    skills = models.TextField(help_text="Comma-separated list of core skills")
    experience_years = models.PositiveIntegerField(default=0)
    
    # Kept nullable for backwards compatibility with older database rows
    education_level = models.CharField(max_length=255, blank=True, null=True)
    
    JOB_TYPE_CHOICES = [
        ('FULL_TIME', 'Full-time'),
        ('PART_TIME', 'Part-time'),
        ('REMOTE', 'Remote'),
        ('CONTRACT', 'Contract'), # Added to support the new frontend dropdown option
    ]
    preferred_job_type = models.CharField(max_length=50, choices=JOB_TYPE_CHOICES)
    preferred_location = models.CharField(max_length=255)

    # --- NEW: Professional Links ---
    linkedin_url = models.URLField(blank=True, null=True)
    github_url = models.URLField(blank=True, null=True)
    portfolio_url = models.URLField(blank=True, null=True)

    # --- NEW: Modular History Arrays stored natively as JSON ---
    experiences = models.JSONField(default=list, blank=True)
    education = models.JSONField(default=list, blank=True)
    projects = models.JSONField(default=list, blank=True)

    def __str__(self):
        return f"Profile for {self.user.username}"

# 3. Job Table
class Job(models.Model):
    job_title = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    job_description = models.TextField()
    required_skills = models.TextField(help_text="Comma-separated list of required skills")
    experience_required = models.PositiveIntegerField(default=0, help_text="Minimum years of experience")
    job_location = models.CharField(max_length=255)
    
    EMPLOYMENT_TYPE_CHOICES = [
        ('FULL_TIME', 'Full-time'),
        ('PART_TIME', 'Part-time'),
        ('CONTRACT', 'Contract'),
        ('REMOTE', 'Remote'),
        ('INTERNSHIP', 'Internship'),
        ('HYBRID', 'Hybrid'),
    ]
    job_type = models.CharField(max_length=50, choices=EMPLOYMENT_TYPE_CHOICES)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.job_title} at {self.company_name}"

# 4. Application Table
class Application(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications')
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='applications')
    
    STATUS_CHOICES = [
        ('APPLIED', 'Applied'),
        ('SHORTLISTED', 'Shortlisted'),
        ('REJECTED', 'Rejected'),
    ]
    application_status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='APPLIED')
    application_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} applied for {self.job.job_title}"

# 5. User_Interaction Table
class UserInteraction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='interactions')
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='interactions')
    
    INTERACTION_CHOICES = [
        ('VIEW', 'View'),
        ('SAVE', 'Save'),
        ('APPLY', 'Apply'),
    ]
    interaction_type = models.CharField(max_length=10, choices=INTERACTION_CHOICES)
    interaction_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} {self.interaction_type} {self.job.job_title}"

# 6. Recommendation Table
class Recommendation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recommendations')
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='recommendations')
    
    recommendation_score = models.FloatField(help_text="Relevance score generated by the AI model")
    generated_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Recommendation: {self.job.job_title} for {self.user.username} (Score: {self.recommendation_score})"

# 7. Feedback Table
class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feedback')
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='feedback')
    
    RATING_CHOICES = [(i, str(i)) for i in range(1, 6)] # Creates choices 1-5
    rating = models.IntegerField(choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    feedback_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Feedback from {self.user.username} on {self.job.job_title} - {self.rating} Stars"